package com.hotelopai.guest.application
import com.hotelopai.observability.OperationalObservability
import com.hotelopai.shared.kernel.UuidV7Generator
import com.hotelopai.task.application.CreateTaskCommand
import com.hotelopai.task.application.TaskLifecycleService
import com.hotelopai.task.domain.*
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate
import org.springframework.stereotype.Service
import org.springframework.transaction.annotation.Transactional
import java.security.MessageDigest
import java.security.SecureRandom
import java.time.Clock
import java.time.Duration
import java.time.Instant
import java.util.Base64
import java.util.UUID

enum class GuestIntent { TOWELS, WATER, PILLOW, HOUSEKEEPING_REQUEST, MAINTENANCE_ISSUE, COMPLAINT, UNKNOWN }
data class IssuedGuestSession(val sessionId:UUID,val opaqueToken:String,val roomNumber:String,val expiresAt:Instant)
data class GuestSessionContext(val id:UUID,val hotelId:UUID,val roomNumber:String,val expiresAt:Instant)
data class GuestMessageResult(val messageId:UUID,val intent:GuestIntent,val taskId:UUID?,val acknowledgement:String)
data class GuestOutboundMessage(val messageId:UUID,val category:String,val deliveryStatus:String,val taskId:UUID?)

@Service class GuestOperationsService(private val jdbc:NamedParameterJdbcTemplate,private val tasks:TaskLifecycleService,private val metrics:OperationalObservability,private val clock:Clock=Clock.systemUTC()){
 private val random=SecureRandom()
 @Transactional fun issue(hotelId:UUID,roomNumber:String,ttl:Duration=Duration.ofHours(24)):IssuedGuestSession { require(roomNumber.isNotBlank());val now=clock.instant();val bytes=ByteArray(32).also(random::nextBytes);val token=Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);val id=UuidV7Generator.generate(now);val expires=now.plus(ttl);jdbc.update("insert into guest_session(id,hotel_id,room_number,token_hash,expires_at,created_at) values(:id,:hotel,:room,:hash,:expires,:now)",mapOf("id" to id,"hotel" to hotelId,"room" to roomNumber,"hash" to hash(token),"expires" to expires,"now" to now));return IssuedGuestSession(id,token,roomNumber,expires) }
 @Transactional fun resolve(token:String):GuestSessionContext { require(token.length in 32..256);val row=jdbc.query("select * from guest_session where token_hash=:hash and revoked_at is null and expires_at>:now",mapOf("hash" to hash(token),"now" to clock.instant())){rs,_->GuestSessionContext(rs.getObject("id",UUID::class.java),rs.getObject("hotel_id",UUID::class.java),rs.getString("room_number"),rs.getTimestamp("expires_at").toInstant())}.firstOrNull()?:throw NoSuchElementException("Guest session not found");enforceRateLimit(row.id);return row }
 @Transactional fun inbound(token:String,providerMessageKey:String,text:String):GuestMessageResult { require(providerMessageKey.isNotBlank());require(text.length in 1..1000);val context=resolve(token);val providerHash=hash(providerMessageKey);existing(providerHash)?.let{return it};val intent=classify(text);val now=clock.instant();val task=if(intent==GuestIntent.UNKNOWN)null else tasks.createTask(CreateTaskCommand(context.hotelId,if(intent==GuestIntent.MAINTENANCE_ISSUE)TaskIntentType.MAINTENANCE else TaskIntentType.GUEST_REQUEST,TaskSource.API,"Guest ${intent.name.lowercase().replace('_',' ')}","Guest-channel request; internal details withheld",context.roomNumber,if(intent==GuestIntent.COMPLAINT)TaskPriority.HIGH else TaskPriority.MEDIUM,now.plusSeconds(1800)));val id=UuidV7Generator.generate(now);jdbc.update("""insert into guest_message(id,hotel_id,guest_session_id,direction,provider,provider_message_key_hash,safe_message_category,normalized_text,delivery_status,task_id,created_at,updated_at)
 values(:id,:hotel,:session,'INBOUND','INTERNAL_DEMO',:key,:category,null,'RECEIVED',:task,:now,:now)""",mapOf("id" to id,"hotel" to context.hotelId,"session" to context.id,"key" to providerHash,"category" to intent.name,"task" to task?.id,"now" to now));metrics.incrementCounter("hotelopai.guest.message.total","operation" to "inbound","outcome" to "accepted","intent" to intent.name.lowercase());val result=GuestMessageResult(id,intent,task?.id,if(task==null)"Your message needs staff confirmation." else "Your request was received by the hotel team.");outbound(context.hotelId,context.id,"REQUEST_ACCEPTED",task?.id,id,"accepted:$providerHash");return result }
 @Transactional fun outbound(hotelId:UUID,sessionId:UUID,category:String,taskId:UUID?=null,linkedMessageId:UUID?=null,idempotencyKey:String):GuestOutboundMessage {require(category.matches(Regex("[A-Z0-9_]{3,64}"))&&idempotencyKey.isNotBlank());val key=hash(idempotencyKey);jdbc.query("select id,safe_message_category,delivery_status,task_id from guest_message where provider='INTERNAL_DEMO' and provider_message_key_hash=:key",mapOf("key" to key)){rs,_->GuestOutboundMessage(rs.getObject(1,UUID::class.java),rs.getString(2),rs.getString(3),rs.getObject(4,UUID::class.java))}.firstOrNull()?.let{return it};val sessionHotel=jdbc.query("select hotel_id from guest_session where id=:id and revoked_at is null",mapOf("id" to sessionId)){rs,_->rs.getObject(1,UUID::class.java)}.firstOrNull();if(sessionHotel!=hotelId)throw NoSuchElementException("Guest session not found");val now=clock.instant();val id=UuidV7Generator.generate(now);jdbc.update("""insert into guest_message(id,hotel_id,guest_session_id,direction,provider,provider_message_key_hash,safe_message_category,delivery_status,task_id,linked_message_id,delivered_at,created_at,updated_at) values(:id,:hotel,:session,'OUTBOUND','INTERNAL_DEMO',:key,:category,'DELIVERED',:task,:linked,:now,:now,:now)""",mapOf("id" to id,"hotel" to hotelId,"session" to sessionId,"key" to key,"category" to category,"task" to taskId,"linked" to linkedMessageId,"now" to now));metrics.incrementCounter("hotelopai.guest.message.total","operation" to "outbound","outcome" to "delivered","category" to category.lowercase());return GuestOutboundMessage(id,category,"DELIVERED",taskId)}
 fun acknowledgeTaskCompleted(hotelId:UUID,sessionId:UUID,taskId:UUID)=outbound(hotelId,sessionId,"REQUEST_COMPLETED",taskId,null,"completed:$sessionId:$taskId")
 @Transactional fun revoke(id:UUID,hotelId:UUID){val changed=jdbc.update("update guest_session set revoked_at=:now where id=:id and hotel_id=:hotel and revoked_at is null",mapOf("now" to clock.instant(),"id" to id,"hotel" to hotelId));if(changed!=1)throw NoSuchElementException("Guest session not found")}
 fun classify(text:String):GuestIntent { val n=text.lowercase();return when{listOf("towel","havlu").any(n::contains)->GuestIntent.TOWELS;listOf("water","su ").any(n::contains)->GuestIntent.WATER;listOf("pillow","yastık","yastik").any(n::contains)->GuestIntent.PILLOW;listOf("clean","housekeep","temiz").any(n::contains)->GuestIntent.HOUSEKEEPING_REQUEST;listOf("broken","leak","air condition","klima","bozuk").any(n::contains)->GuestIntent.MAINTENANCE_ISSUE;listOf("complaint","unhappy","şikayet","sikayet").any(n::contains)->GuestIntent.COMPLAINT;else->GuestIntent.UNKNOWN} }
 private fun enforceRateLimit(id:UUID){val now=clock.instant();val row=jdbc.query("select rate_limit_window_start,rate_limit_count from guest_session where id=:id for update",mapOf("id" to id)){rs,_->rs.getTimestamp(1)?.toInstant() to rs.getInt(2)}.first();val reset=row.first==null||Duration.between(row.first,now)>Duration.ofMinutes(1);val count=if(reset)1 else row.second+1;require(count<=30){"Guest session rate limit exceeded"};jdbc.update("update guest_session set last_used_at=:now,rate_limit_window_start=:window,rate_limit_count=:count where id=:id",mapOf("now" to now,"window" to if(reset)now else row.first,"count" to count,"id" to id)) }
 private fun existing(key:String)=jdbc.query("select id,safe_message_category,task_id from guest_message where provider='INTERNAL_DEMO' and provider_message_key_hash=:key",mapOf("key" to key)){rs,_->GuestMessageResult(rs.getObject(1,UUID::class.java),GuestIntent.valueOf(rs.getString(2)),rs.getObject(3,UUID::class.java),"Your request was already received.")}.firstOrNull()
 private fun hash(value:String)=MessageDigest.getInstance("SHA-256").digest(value.toByteArray()).joinToString(""){"%02x".format(it)}
}
