package com.hotelopai.gamification.application
import com.hotelopai.shared.kernel.UuidV7Generator
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate
import org.springframework.stereotype.Service
import org.springframework.transaction.annotation.Transactional
import java.time.*
import java.time.temporal.TemporalAdjusters
import java.util.UUID
enum class GamificationPeriod { DAILY, WEEKLY, MONTHLY }
data class AwardXpCommand(val hotelId:UUID,val employeeId:UUID,val sourceReference:String,val completed:Boolean,val slaSuccess:Boolean,val qualityScore:Int?,val firstTimeSuccess:Boolean,val vip:Boolean=false,val maintenance:Boolean=false,val guestHappiness:Boolean=false,val teamContribution:Boolean=false)
data class GamificationAward(val xp:Int,val badges:List<String>)
data class LeaderboardRow(val employeeId:UUID,val displayName:String,val rank:Int,val xp:Long,val completedTaskCount:Long,val qualityIndicator:Double?,val badges:List<String>)
private data class RawLeaderboardRow(val employeeId:UUID,val displayName:String,val xp:Long,val completed:Long,val quality:Double?)
@Service class GamificationService(private val jdbc:NamedParameterJdbcTemplate,private val clock:Clock=Clock.systemUTC()){
 @Transactional fun award(c:AwardXpCommand):GamificationAward {require(c.sourceReference.isNotBlank());existing(c)?.let{return it};var xp=if(c.completed)20 else 0;if(c.slaSuccess)xp+=15;if(c.firstTimeSuccess)xp+=20;xp+=when{(c.qualityScore?:0)>=95->30;(c.qualityScore?:0)>=80->15;else->0};val now=clock.instant();jdbc.update("insert into gamification_ledger(id,hotel_id,employee_id,event_type,source_reference,xp,quality_score,occurred_at,rule_version) values(:id,:hotel,:employee,'TASK_QUALITY',:source,:xp,:quality,:now,'mvp-v1')",mapOf("id" to UuidV7Generator.generate(now),"hotel" to c.hotelId,"employee" to c.employeeId,"source" to c.sourceReference,"xp" to xp,"quality" to c.qualityScore,"now" to now));val badges=buildList{if(c.completed&&c.slaSuccess&&(c.qualityScore?:0)>=90)add("LIGHTNING_CLEANER");if(c.vip&&(c.qualityScore?:0)>=90)add("VIP_MASTER");if(c.maintenance&&c.firstTimeSuccess)add("MAINTENANCE_HERO");if(c.guestHappiness)add("GUEST_HAPPINESS");if(c.teamContribution)add("TEAM_PLAYER")};badges.forEach{badge->jdbc.update("insert into employee_badge(hotel_id,employee_id,badge_code,earned_at,source_reference) values(:hotel,:employee,:badge,:now,:source) on conflict do nothing",mapOf("hotel" to c.hotelId,"employee" to c.employeeId,"badge" to badge,"now" to now,"source" to c.sourceReference))};return GamificationAward(xp,badges)}
 fun leaderboard(hotelId:UUID,period:GamificationPeriod,departmentId:UUID?=null):List<LeaderboardRow>{val zone=ZoneOffset.UTC;val today=LocalDate.now(clock);val start=when(period){GamificationPeriod.DAILY->today.atStartOfDay(zone).toInstant();GamificationPeriod.WEEKLY->today.with(java.time.DayOfWeek.MONDAY).atStartOfDay(zone).toInstant();GamificationPeriod.MONTHLY->today.with(TemporalAdjusters.firstDayOfMonth()).atStartOfDay(zone).toInstant()};val rows=jdbc.query("""select e.id,e.display_name,sum(g.xp) xp,count(*) completed,avg(g.quality_score) quality from gamification_ledger g join employee e on e.id=g.employee_id where g.hotel_id=:hotel and g.occurred_at>=:start and (:department is null or e.department_id=:department) group by e.id,e.display_name order by xp desc,e.display_name""",mapOf("hotel" to hotelId,"start" to start,"department" to departmentId)){rs,_->val quality=rs.getDouble(5);RawLeaderboardRow(rs.getObject(1,UUID::class.java),rs.getString(2),rs.getLong(3),rs.getLong(4),quality.takeUnless{rs.wasNull()})};return rows.mapIndexed{i,r->LeaderboardRow(r.employeeId,r.displayName,i+1,r.xp,r.completed,r.quality,badges(hotelId,r.employeeId))}}
 private fun badges(hotel:UUID,employee:UUID):List<String> = jdbc.query("select badge_code from employee_badge where hotel_id=:hotel and employee_id=:employee order by earned_at",mapOf("hotel" to hotel,"employee" to employee)){rs,_->rs.getString(1)}.filterNotNull()
 private fun existing(c:AwardXpCommand)=jdbc.query("select xp from gamification_ledger where hotel_id=:hotel and source_reference=:source and event_type='TASK_QUALITY'",mapOf("hotel" to c.hotelId,"source" to c.sourceReference)){rs,_->GamificationAward(rs.getInt(1),emptyList())}.firstOrNull()
}
