package com.hotelopai.masterdata.application

import com.hotelopai.shared.kernel.UuidV7Generator
import com.hotelopai.auth.application.PasswordHasher
import org.springframework.dao.DataIntegrityViolationException
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate
import org.springframework.stereotype.Service
import org.springframework.transaction.annotation.Transactional
import java.time.Clock
import java.time.LocalDate
import java.time.LocalTime
import java.util.UUID

class MasterDataConflict(message: String) : RuntimeException(message)
class MasterDataNotFound(message: String) : RuntimeException(message)
class InactiveHotel : RuntimeException("Operational master data cannot be created for an inactive hotel")

data class HotelView(val id: UUID, val code: String, val name: String, val timezone: String, val address: String?, val active: Boolean)
data class BuildingView(val id: UUID, val code: String, val name: String, val active: Boolean)
data class FloorView(val id: UUID, val buildingId: UUID, val floorNumber: Int, val name: String?, val active: Boolean)
data class RoomView(val id: UUID, val buildingId: UUID, val floorId: UUID, val roomNumber: String, val roomType: String?, val active: Boolean)
data class PageView<T>(val items: List<T>, val page: Int, val size: Int, val totalItems: Long)
data class NamedView(val id: UUID, val code: String, val name: String, val description: String? = null, val active: Boolean = true)
data class PermissionView(val id:UUID,val code:String,val name:String,val assigned:Boolean)
data class HotelAccessView(val roleCodes:Set<String>,val permissionCodes:Set<String>)
data class MembershipView(val id: UUID, val userId: UUID, val email: String, val displayName: String, val departmentId: UUID?, val active: Boolean)
data class MembershipRoleView(val id:UUID,val code:String,val name:String)
data class MembershipSkillView(val id:UUID,val code:String,val name:String,val skillLevel:String?,val active:Boolean)
data class MembershipDetailView(val membership:MembershipView,val roles:List<MembershipRoleView>,val skills:List<MembershipSkillView>,val shifts:List<ShiftAssignmentView>)
data class ShiftView(val id: UUID, val code: String, val name: String, val startTime: LocalTime, val endTime: LocalTime, val active: Boolean, val crossesMidnight: Boolean)
data class ShiftAssignmentView(val id: UUID, val membershipId: UUID, val shiftId: UUID, val shiftDate: LocalDate, val active: Boolean)
data class ImportRowResult(val row: Int, val status: String, val message: String? = null)
data class RoomImportResult(val processed: Int, val imported: Int, val duplicates: Int, val invalid: Int, val rows: List<ImportRowResult>)
data class OnboardingDepartment(val code:String,val name:String)
data class OnboardingBuilding(val code:String,val name:String,val floors:List<Int>)
data class OnboardingRoom(val buildingCode:String,val floorNumber:Int,val roomNumber:String,val roomType:String?)
data class OnboardingSkill(val code:String,val name:String,val description:String?)
data class OnboardingShift(val code:String,val name:String,val startTime:LocalTime,val endTime:LocalTime)
data class HotelOnboardingCommand(val code:String,val name:String,val timezone:String,val address:String?,val departments:List<OnboardingDepartment>,val buildings:List<OnboardingBuilding>,val rooms:List<OnboardingRoom>,val skills:List<OnboardingSkill>,val shifts:List<OnboardingShift>,val administratorUserId:UUID,val administratorRoleId:UUID?)
data class HotelOnboardingResult(val hotel:HotelView,val departmentCount:Int,val buildingCount:Int,val floorCount:Int,val roomCount:Int,val skillCount:Int,val shiftCount:Int,val administratorMembershipId:UUID)

@Service
class MasterDataAdminService(private val jdbc: NamedParameterJdbcTemplate, private val clock: Clock,private val passwordHasher:PasswordHasher) {
    @Transactional(readOnly=true) fun access(userId:UUID,hotelId:UUID):HotelAccessView {val roles=jdbc.query("select distinct r.code from user_hotel_membership m join user_hotel_role uhr on uhr.membership_id=m.id and uhr.hotel_id=m.hotel_id join role r on r.id=uhr.role_id where m.user_id=:user and m.hotel_id=:hotel and m.active=true and r.is_active=true",mapOf("user" to userId,"hotel" to hotelId)){r,_->r.getString(1)}.toSet();val permissions=jdbc.query("select distinct p.code from user_hotel_membership m join user_hotel_role uhr on uhr.membership_id=m.id and uhr.hotel_id=m.hotel_id join role_permission rp on rp.role_id=uhr.role_id join permission p on p.id=rp.permission_id where m.user_id=:user and m.hotel_id=:hotel and m.active=true",mapOf("user" to userId,"hotel" to hotelId)){r,_->r.getString(1)}.toSet();return HotelAccessView(roles,permissions)}
    @Transactional
    fun onboard(command:HotelOnboardingCommand,actor:UUID):HotelOnboardingResult {
        val hotel=createHotel(command.code,command.name,command.timezone,command.address,actor)
        command.departments.forEach{createNamed("department",hotel.id,it.code,it.name,null,actor)}
        val buildingIds=mutableMapOf<String,UUID>();val floorIds=mutableMapOf<Pair<String,Int>,UUID>()
        command.buildings.forEach{b->val building=createBuilding(hotel.id,b.code,b.name,actor);buildingIds[b.code.uppercase()]=building.id;b.floors.distinct().forEach{n->floorIds[b.code.uppercase() to n]=createFloor(hotel.id,building.id,n,null,actor).id}}
        command.rooms.forEach{r->val key=r.buildingCode.uppercase() to r.floorNumber;createRoom(hotel.id,buildingIds[key.first]?:throw IllegalArgumentException("Unknown onboarding building ${r.buildingCode}"),floorIds[key]?:throw IllegalArgumentException("Unknown onboarding floor ${r.floorNumber}"),r.roomNumber,r.roomType,actor)}
        command.skills.forEach{createNamed("skill",hotel.id,it.code,it.name,it.description,actor)}
        command.shifts.forEach{createShift(hotel.id,it.code,it.name,it.startTime,it.endTime,actor)}
        val membership=addMembership(hotel.id,command.administratorUserId,null,actor)
        val adminRoleId=command.administratorRoleId ?: createDefaultHotelAdminRole(hotel.id,actor)
        assignRole(hotel.id,membership.id,adminRoleId,actor)
        return HotelOnboardingResult(hotel,command.departments.size,command.buildings.size,floorIds.size,command.rooms.size,command.skills.size,command.shifts.size,membership.id)
    }
    @Transactional(readOnly = true)
    fun hotelsFor(userId: UUID, platformView: Boolean): List<HotelView> = jdbc.query(
        if (platformView) "select * from hotel order by name" else """select h.* from hotel h join user_hotel_membership m on m.hotel_id=h.id where m.user_id=:user and m.active=true order by h.name""",
        mapOf("user" to userId)
    ) { rs, _ -> HotelView(rs.getObject("id", UUID::class.java), rs.getString("code"), rs.getString("name"), rs.getString("timezone"), rs.getString("address"), rs.getString("status") == "ACTIVE") }

    @Transactional
    fun createHotel(code: String, name: String, timezone: String, address: String?, actor: UUID): HotelView = guarded {
        require(code.matches(Regex("[A-Z0-9_]{2,32}"))) { "code must contain 2-32 uppercase letters, numbers, or underscores" }
        java.time.ZoneId.of(timezone)
        val id = UuidV7Generator.generate(clock.instant()); val now = clock.instant()
        jdbc.update("""insert into hotel(id,version,created_at,created_by,updated_at,updated_by,code,name,status,timezone,address) values(:id,0,:now,:actor,:now,:actor,:code,:name,'ACTIVE',:timezone,:address)""",
            mapOf("id" to id,"now" to now,"actor" to actor.toString(),"code" to code,"name" to name.trim(),"timezone" to timezone,"address" to address?.trim()?.takeIf(String::isNotEmpty)))
        hotel(id)
    }

    @Transactional(readOnly = true) fun hotel(id: UUID): HotelView = jdbc.query("select * from hotel where id=:id", mapOf("id" to id)) { rs, _ -> HotelView(rs.getObject("id",UUID::class.java),rs.getString("code"),rs.getString("name"),rs.getString("timezone"),rs.getString("address"),rs.getString("status")=="ACTIVE") }.firstOrNull() ?: throw MasterDataNotFound("Hotel not found")
    @Transactional fun updateHotel(id: UUID, name: String, timezone: String, address: String?, active: Boolean, actor: UUID): HotelView { java.time.ZoneId.of(timezone); if(jdbc.update("update hotel set name=:name,timezone=:timezone,address=:address,status=:status,updated_at=:now,updated_by=:actor,version=version+1 where id=:id",mapOf("id" to id,"name" to name.trim(),"timezone" to timezone,"address" to address,"status" to if(active)"ACTIVE" else "INACTIVE","now" to clock.instant(),"actor" to actor.toString()))==0) throw MasterDataNotFound("Hotel not found"); return hotel(id) }

    @Transactional fun createBuilding(hotelId: UUID, code: String, name: String, actor: UUID): BuildingView = guarded { requireActive(hotelId); val id=newId(); stampInsert("building",id,hotelId,actor,"code,name", mapOf("code" to normalized(code),"name" to name.trim())); building(hotelId,id) }
    @Transactional(readOnly=true) fun buildings(hotelId: UUID):List<BuildingView> = jdbc.query("select * from building where hotel_id=:hotel order by code",mapOf("hotel" to hotelId)){r,_->BuildingView(r.uuid("id"),r.getString("code"),r.getString("name"),r.getBoolean("active"))}
    @Transactional(readOnly=true) fun building(hotelId:UUID,id:UUID)=jdbc.query("select * from building where hotel_id=:hotel and id=:id",mapOf("hotel" to hotelId,"id" to id)){r,_->BuildingView(r.uuid("id"),r.getString("code"),r.getString("name"),r.getBoolean("active"))}.firstOrNull()?:throw MasterDataNotFound("Building not found")
    @Transactional fun updateBuilding(hotelId:UUID,id:UUID,code:String,name:String,active:Boolean,actor:UUID):BuildingView=guarded{ updateNamed("building",hotelId,id,code,name,null,active,actor);building(hotelId,id)}

    @Transactional fun createFloor(hotelId:UUID,buildingId:UUID,number:Int,name:String?,actor:UUID):FloorView=guarded{requireActive(hotelId);building(hotelId,buildingId);val id=newId();stampInsert("hotel_floor",id,hotelId,actor,"building_id,floor_number,name",mapOf("building_id" to buildingId,"floor_number" to number,"name" to name));floor(hotelId,id)}
    @Transactional(readOnly=true) fun floors(hotelId:UUID,buildingId:UUID?)=jdbc.query("select * from hotel_floor where hotel_id=:hotel and (:building is null or building_id=:building) order by floor_number",mapOf("hotel" to hotelId,"building" to buildingId)){r,_->FloorView(r.uuid("id"),r.uuid("building_id"),r.getInt("floor_number"),r.getString("name"),r.getBoolean("active"))}
    @Transactional(readOnly=true) fun floor(hotelId:UUID,id:UUID)=jdbc.query("select * from hotel_floor where hotel_id=:hotel and id=:id",mapOf("hotel" to hotelId,"id" to id)){r,_->FloorView(r.uuid("id"),r.uuid("building_id"),r.getInt("floor_number"),r.getString("name"),r.getBoolean("active"))}.firstOrNull()?:throw MasterDataNotFound("Floor not found")
    @Transactional fun updateFloor(hotelId:UUID,id:UUID,buildingId:UUID,number:Int,name:String?,active:Boolean,actor:UUID):FloorView=guarded{building(hotelId,buildingId);if(jdbc.update("update hotel_floor set building_id=:building,floor_number=:number,name=:name,active=:active,updated_at=:now,updated_by=:actor where id=:id and hotel_id=:hotel",mapOf("hotel" to hotelId,"id" to id,"building" to buildingId,"number" to number,"name" to name,"active" to active,"now" to clock.instant(),"actor" to actor.toString()))==0)throw MasterDataNotFound("Floor not found");floor(hotelId,id)}

    @Transactional fun createRoom(hotelId:UUID,buildingId:UUID,floorId:UUID,number:String,type:String?,actor:UUID):RoomView=guarded{requireActive(hotelId); val floor=floor(hotelId,floorId);require(floor.buildingId==buildingId){"Floor does not belong to building"};val id=newId();stampInsert("room_master",id,hotelId,actor,"building_id,floor_id,room_number,room_type",mapOf("building_id" to buildingId,"floor_id" to floorId,"room_number" to number.trim(),"room_type" to type?.trim()?.uppercase()));room(hotelId,id)}
    @Transactional(readOnly=true) fun room(hotelId:UUID,id:UUID)=jdbc.query("select * from room_master where hotel_id=:hotel and id=:id",mapOf("hotel" to hotelId,"id" to id)){r,_->RoomView(r.uuid("id"),r.uuid("building_id"),r.uuid("floor_id"),r.getString("room_number"),r.getString("room_type"),r.getBoolean("active"))}.firstOrNull()?:throw MasterDataNotFound("Room not found")
    @Transactional(readOnly=true) fun rooms(hotelId:UUID,q:String?,buildingId:UUID?,floorId:UUID?,type:String?,active:Boolean?,page:Int,size:Int):PageView<RoomView>{val p=page.coerceAtLeast(0);val s=size.coerceIn(1,100);val params=mapOf("hotel" to hotelId,"q" to q?.trim()?.takeIf(String::isNotEmpty),"building" to buildingId,"floor" to floorId,"type" to type?.uppercase(),"active" to active,"limit" to s,"offset" to p*s);val where="hotel_id=:hotel and (:q is null or lower(room_number) like lower('%'||:q||'%')) and (:building is null or building_id=:building) and (:floor is null or floor_id=:floor) and (:type is null or room_type=:type) and (:active is null or active=:active)";val items=jdbc.query("select * from room_master where $where order by room_number limit :limit offset :offset",params){r,_->RoomView(r.uuid("id"),r.uuid("building_id"),r.uuid("floor_id"),r.getString("room_number"),r.getString("room_type"),r.getBoolean("active"))};val total=jdbc.queryForObject("select count(*) from room_master where $where",params,Long::class.java)?:0;return PageView(items,p,s,total)}
    @Transactional fun updateRoom(hotelId:UUID,id:UUID,buildingId:UUID,floorId:UUID,number:String,type:String?,active:Boolean,actor:UUID):RoomView=guarded{val f=floor(hotelId,floorId);require(f.buildingId==buildingId){"Floor does not belong to building"};if(jdbc.update("update room_master set building_id=:building,floor_id=:floor,room_number=:number,room_type=:type,active=:active,updated_at=:now,updated_by=:actor where id=:id and hotel_id=:hotel",mapOf("hotel" to hotelId,"id" to id,"building" to buildingId,"floor" to floorId,"number" to number.trim(),"type" to type?.uppercase(),"active" to active,"now" to clock.instant(),"actor" to actor.toString()))==0)throw MasterDataNotFound("Room not found");room(hotelId,id)}

    @Transactional fun createNamed(kind:String,hotelId:UUID,code:String,name:String,description:String?,actor:UUID):NamedView=guarded{require(kind in setOf("department","skill","role"));requireActive(hotelId);val id=newId();val now=clock.instant();val descriptionColumn=if(kind=="department")"" else ",description";val descriptionValue=if(kind=="department")"" else ",:description";jdbc.update("insert into $kind(id,hotel_id,version,created_at,created_by,updated_at,updated_by,code,name$descriptionColumn,is_active) values(:id,:hotel,0,:now,:actor,:now,:actor,:code,:name$descriptionValue,true)",mapOf("id" to id,"hotel" to hotelId,"now" to now,"actor" to actor.toString(),"code" to normalized(code),"name" to name.trim(),"description" to description));named(kind,hotelId,id)}
    @Transactional(readOnly=true) fun namedList(kind:String,hotelId:UUID):List<NamedView>{require(kind in setOf("department","skill","role"));val description=if(kind=="department")"null::text" else "description";return jdbc.query("select id,code,name,$description description,is_active active from $kind where hotel_id=:hotel order by code",mapOf("hotel" to hotelId)){r,_->NamedView(r.uuid("id"),r.getString("code"),r.getString("name"),r.getString("description"),r.getBoolean("active"))}}
    @Transactional(readOnly=true) fun named(kind:String,hotelId:UUID,id:UUID)=namedList(kind,hotelId).firstOrNull{it.id==id}?:throw MasterDataNotFound("${kind.replaceFirstChar(Char::uppercase)} not found")
    @Transactional fun updateNamedRecord(kind:String,hotelId:UUID,id:UUID,code:String,name:String,description:String?,active:Boolean,actor:UUID):NamedView=guarded{require(kind in setOf("department","skill","role"));updateNamed(kind,hotelId,id,code,name,description,active,actor);named(kind,hotelId,id)}
    @Transactional(readOnly=true) fun rolePermissions(hotelId:UUID,roleId:UUID):List<PermissionView>{named("role",hotelId,roleId);return jdbc.query("select p.id,p.code,p.name,exists(select 1 from role_permission rp where rp.role_id=:role and rp.permission_id=p.id) assigned from permission p order by p.code",mapOf("role" to roleId)){r,_->PermissionView(r.uuid("id"),r.getString("code"),r.getString("name"),r.getBoolean("assigned"))}}
    @Transactional fun replaceRolePermissions(hotelId:UUID,roleId:UUID,permissionIds:Set<UUID>){named("role",hotelId,roleId);val valid=jdbc.queryForObject("select count(*) from permission where id in (:ids)",mapOf("ids" to permissionIds.ifEmpty{setOf(UUID(0,0))}),Long::class.java)?:0;require(valid==permissionIds.size.toLong()){ "Unknown permission"};jdbc.update("delete from role_permission where role_id=:role",mapOf("role" to roleId));permissionIds.forEach{jdbc.update("insert into role_permission(role_id,permission_id) values(:role,:permission)",mapOf("role" to roleId,"permission" to it))}}

    @Transactional fun createShift(hotelId:UUID,code:String,name:String,start:LocalTime,end:LocalTime,actor:UUID):ShiftView=guarded{requireActive(hotelId);val id=newId();stampInsert("shift_definition",id,hotelId,actor,"code,name,start_time,end_time",mapOf("code" to normalized(code),"name" to name.trim(),"start_time" to start,"end_time" to end));shift(hotelId,id)}
    @Transactional(readOnly=true) fun shifts(hotelId:UUID)=jdbc.query("select * from shift_definition where hotel_id=:hotel order by start_time",mapOf("hotel" to hotelId)){r,_->shiftRow(r)}
    @Transactional(readOnly=true) fun shift(hotelId:UUID,id:UUID)=jdbc.query("select * from shift_definition where hotel_id=:hotel and id=:id",mapOf("hotel" to hotelId,"id" to id)){r,_->shiftRow(r)}.firstOrNull()?:throw MasterDataNotFound("Shift not found")

    @Transactional fun addMembership(hotelId:UUID,userId:UUID,departmentId:UUID?,actor:UUID):MembershipView=guarded{requireActive(hotelId);departmentId?.let{named("department",hotelId,it)};val id=newId();val now=clock.instant();jdbc.update("insert into user_hotel_membership(id,user_id,hotel_id,department_id,active,created_at,created_by,updated_at,updated_by) values(:id,:user,:hotel,:department,true,:now,:actor,:now,:actor)",mapOf("id" to id,"user" to userId,"hotel" to hotelId,"department" to departmentId,"now" to now,"actor" to actor.toString()));membership(hotelId,id)}
    @Transactional fun addOrCreateUser(hotelId:UUID,email:String,displayName:String,initialPassword:String,departmentId:UUID?,actor:UUID):MembershipView{require(initialPassword.length>=8){"Initial password must contain at least 8 characters"};val normalized=email.trim().lowercase();require(normalized.contains('@')){"Invalid email"};val existing=jdbc.query("select id from app_user where lower(email)=:email order by created_at limit 1",mapOf("email" to normalized)){r,_->r.uuid("id")}.firstOrNull();val userId=existing?:run{val id=newId();val now=clock.instant();jdbc.update("insert into app_user(id,hotel_id,version,created_at,created_by,updated_at,updated_by,email,display_name,password_hash,status) values(:id,:hotel,0,:now,:actor,:now,:actor,:email,:name,:password,'ACTIVE')",mapOf("id" to id,"hotel" to hotelId,"now" to now,"actor" to actor.toString(),"email" to normalized,"name" to displayName.trim(),"password" to passwordHasher.hash(initialPassword)));id};return addMembership(hotelId,userId,departmentId,actor)}
    @Transactional(readOnly=true) fun memberships(hotelId:UUID)=jdbc.query("select m.*,u.email,u.display_name from user_hotel_membership m join app_user u on u.id=m.user_id where m.hotel_id=:hotel order by u.display_name",mapOf("hotel" to hotelId)){r,_->MembershipView(r.uuid("id"),r.uuid("user_id"),r.getString("email"),r.getString("display_name"),r.getObject("department_id",UUID::class.java),r.getBoolean("active"))}
    @Transactional(readOnly=true) fun membership(hotelId:UUID,id:UUID)=memberships(hotelId).firstOrNull{it.id==id}?:throw MasterDataNotFound("Membership not found")
    @Transactional(readOnly=true) fun membershipDetail(hotelId:UUID,id:UUID):MembershipDetailView {val m=membership(hotelId,id);val roles=jdbc.query("select r.id,r.code,r.name from user_hotel_role uhr join role r on r.id=uhr.role_id where uhr.membership_id=:membership and uhr.hotel_id=:hotel order by r.code",mapOf("membership" to id,"hotel" to hotelId)){r,_->MembershipRoleView(r.uuid("id"),r.getString("code"),r.getString("name"))};val skills=jdbc.query("select s.id,s.code,s.name,uhs.skill_level,uhs.active from user_hotel_skill uhs join skill s on s.id=uhs.skill_id where uhs.membership_id=:membership and uhs.hotel_id=:hotel order by s.code",mapOf("membership" to id,"hotel" to hotelId)){r,_->MembershipSkillView(r.uuid("id"),r.getString("code"),r.getString("name"),r.getString("skill_level"),r.getBoolean("active"))};return MembershipDetailView(m,roles,skills,shiftAssignments(hotelId,null,id,null)) }
    @Transactional fun updateMembership(hotelId:UUID,id:UUID,displayName:String?,departmentId:UUID?,active:Boolean,actor:UUID):MembershipDetailView {val existing=membership(hotelId,id);departmentId?.let{named("department",hotelId,it)};val now=clock.instant();jdbc.update("update user_hotel_membership set department_id=:department,active=:active,updated_at=:now,updated_by=:actor where id=:id and hotel_id=:hotel",mapOf("id" to id,"hotel" to hotelId,"department" to departmentId,"active" to active,"now" to now,"actor" to actor.toString()));displayName?.trim()?.takeIf(String::isNotEmpty)?.let{jdbc.update("update app_user set display_name=:name,updated_at=:now,updated_by=:actor,version=version+1 where id=:user",mapOf("name" to it,"now" to now,"actor" to actor.toString(),"user" to existing.userId))};return membershipDetail(hotelId,id)}
    @Transactional fun replaceMembershipRoles(hotelId:UUID,membershipId:UUID,roleIds:Set<UUID>,actor:UUID):MembershipDetailView {membership(hotelId,membershipId);roleIds.forEach{named("role",hotelId,it)};jdbc.update("delete from user_hotel_role where membership_id=:membership and hotel_id=:hotel",mapOf("membership" to membershipId,"hotel" to hotelId));roleIds.forEach{assignRole(hotelId,membershipId,it,actor)};return membershipDetail(hotelId,membershipId)}
    @Transactional fun replaceMembershipSkills(hotelId:UUID,membershipId:UUID,skills:Map<UUID,String?>,actor:UUID):MembershipDetailView {membership(hotelId,membershipId);skills.keys.forEach{named("skill",hotelId,it)};jdbc.update("delete from user_hotel_skill where membership_id=:membership and hotel_id=:hotel",mapOf("membership" to membershipId,"hotel" to hotelId));skills.forEach{(id,level)->assignSkill(hotelId,membershipId,id,level,actor)};return membershipDetail(hotelId,membershipId)}
    @Transactional fun assignRole(hotelId:UUID,membershipId:UUID,roleId:UUID,actor:UUID){membership(hotelId,membershipId);named("role",hotelId,roleId);guarded{jdbc.update("insert into user_hotel_role(id,membership_id,role_id,hotel_id,created_at,created_by) values(:id,:membership,:role,:hotel,:now,:actor)",mapOf("id" to newId(),"membership" to membershipId,"role" to roleId,"hotel" to hotelId,"now" to clock.instant(),"actor" to actor.toString()))}}
    @Transactional fun assignSkill(hotelId:UUID,membershipId:UUID,skillId:UUID,level:String?,actor:UUID){membership(hotelId,membershipId);named("skill",hotelId,skillId);val normalized=level?.uppercase();require(normalized==null||normalized in setOf("BEGINNER","INTERMEDIATE","ADVANCED","EXPERT"));guarded{val now=clock.instant();jdbc.update("insert into user_hotel_skill(id,membership_id,skill_id,hotel_id,skill_level,active,created_at,created_by,updated_at,updated_by) values(:id,:membership,:skill,:hotel,:level,true,:now,:actor,:now,:actor)",mapOf("id" to newId(),"membership" to membershipId,"skill" to skillId,"hotel" to hotelId,"level" to normalized,"now" to now,"actor" to actor.toString()))}}
    @Transactional fun assignShift(hotelId:UUID,membershipId:UUID,shiftId:UUID,date:LocalDate,actor:UUID):ShiftAssignmentView=guarded{membership(hotelId,membershipId);shift(hotelId,shiftId);val id=newId();val now=clock.instant();jdbc.update("insert into user_shift_assignment(id,membership_id,hotel_id,shift_id,shift_date,active,created_at,created_by,updated_at,updated_by) values(:id,:membership,:hotel,:shift,:date,true,:now,:actor,:now,:actor)",mapOf("id" to id,"membership" to membershipId,"hotel" to hotelId,"shift" to shiftId,"date" to date,"now" to now,"actor" to actor.toString()));ShiftAssignmentView(id,membershipId,shiftId,date,true)}
    @Transactional(readOnly=true) fun shiftAssignments(hotelId:UUID,date:LocalDate?,membershipId:UUID?,shiftId:UUID?)=jdbc.query("select * from user_shift_assignment where hotel_id=:hotel and (:date is null or shift_date=:date) and (:membership is null or membership_id=:membership) and (:shift is null or shift_id=:shift) order by shift_date",mapOf("hotel" to hotelId,"date" to date,"membership" to membershipId,"shift" to shiftId)){r,_->ShiftAssignmentView(r.uuid("id"),r.uuid("membership_id"),r.uuid("shift_id"),r.getObject("shift_date",LocalDate::class.java),r.getBoolean("active"))}

    @Transactional fun importRooms(hotelId:UUID,csv:String,actor:UUID):RoomImportResult{requireActive(hotelId);val lines=csv.lineSequence().filter(String::isNotBlank).toList();require(lines.isNotEmpty()&&lines.first().replace(" ","").equals("building,floor,roomNumber,roomType",true)){"CSV header must be building,floor,roomNumber,roomType"};val rows=mutableListOf<ImportRowResult>();var imported=0;var duplicate=0;var invalid=0;lines.drop(1).forEachIndexed{i,line->val cells=line.split(',').map(String::trim);try{require(cells.size==4);val building=buildings(hotelId).firstOrNull{it.code.equals(cells[0],true)}?:error("Unknown building");val floor=floors(hotelId,building.id).firstOrNull{it.floorNumber==cells[1].toInt()}?:error("Unknown floor");createRoom(hotelId,building.id,floor.id,cells[2],cells[3].takeIf(String::isNotBlank),actor);imported++;rows+=ImportRowResult(i+2,"IMPORTED")}catch(e:MasterDataConflict){duplicate++;rows+=ImportRowResult(i+2,"DUPLICATE",e.message)}catch(e:RuntimeException){invalid++;rows+=ImportRowResult(i+2,"INVALID",e.message)}};return RoomImportResult(lines.size-1,imported,duplicate,invalid,rows)}

    private fun requireActive(hotelId:UUID){if(!hotel(hotelId).active)throw InactiveHotel()}
    private fun createDefaultHotelAdminRole(hotelId:UUID,actor:UUID):UUID { val role=createNamed("role",hotelId,"HOTEL_ADMIN","Hotel Admin","Hotel-scoped administrator",actor);jdbc.update("insert into role_permission(role_id,permission_id) select :role,id from permission where code in ('HOTEL_VIEW','HOTEL_MANAGE','BUILDING_VIEW','BUILDING_MANAGE','FLOOR_VIEW','FLOOR_MANAGE','ROOM_VIEW','ROOM_CREATE','ROOM_UPDATE','ROOM_DELETE','DEPARTMENT_VIEW','DEPARTMENT_MANAGE','USER_VIEW','USER_CREATE','USER_UPDATE','USER_ASSIGN','ROLE_VIEW','ROLE_MANAGE','SKILL_VIEW','SKILL_MANAGE','SHIFT_VIEW','SHIFT_MANAGE') on conflict do nothing",mapOf("role" to role.id));return role.id }
    private fun normalized(value:String)=value.trim().uppercase().also{require(it.matches(Regex("[A-Z0-9_]{1,64}"))){"Invalid code"}}
    private fun newId()=UuidV7Generator.generate(clock.instant())
    private fun stampInsert(table:String,id:UUID,hotelId:UUID,actor:UUID,columns:String,values:Map<String,Any?>){val now=clock.instant();val names=columns.split(',');val sql="insert into $table(id,hotel_id,${names.joinToString(",")},created_at,created_by,updated_at,updated_by) values(:id,:hotel,${names.joinToString(","){":$it"}},:now,:actor,:now,:actor)";jdbc.update(sql,MapSqlParameterSource(values+mapOf("id" to id,"hotel" to hotelId,"now" to now,"actor" to actor.toString())))}
    private fun updateNamed(table:String,hotelId:UUID,id:UUID,code:String,name:String,description:String?,active:Boolean,actor:UUID){val desc=if(table=="department")"" else ",description=:description";if(jdbc.update("update $table set code=:code,name=:name$desc,is_active=:active,updated_at=:now,updated_by=:actor where id=:id and hotel_id=:hotel",mapOf("id" to id,"hotel" to hotelId,"code" to normalized(code),"name" to name.trim(),"description" to description,"active" to active,"now" to clock.instant(),"actor" to actor.toString()))==0)throw MasterDataNotFound("Record not found")}
    private fun shiftRow(r:java.sql.ResultSet)=ShiftView(r.uuid("id"),r.getString("code"),r.getString("name"),r.getObject("start_time",LocalTime::class.java),r.getObject("end_time",LocalTime::class.java),r.getBoolean("active"),!r.getObject("end_time",LocalTime::class.java).isAfter(r.getObject("start_time",LocalTime::class.java)))
    private fun java.sql.ResultSet.uuid(name:String)=getObject(name,UUID::class.java)
    private fun <T> guarded(block:()->T):T=try{block()}catch(e:DataIntegrityViolationException){throw MasterDataConflict("Duplicate or cross-hotel relationship")}
}
