import { useEffect, useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { createMobileHotelOpAiClient } from "../../api/hotelOpAiClient";
import { InspectionApi, InspectionAnswer, InspectionDetail, InspectionWorkflow } from "../../api/housekeeping/InspectionApi";
import { CurrentUserSnapshot } from "../../session/sessionTypes";
import { colors, spacing } from "../../theme/tokens";

export function InspectionsScreen({ accessToken, currentUser, refreshAccessToken }: { accessToken: string | null; currentUser: CurrentUserSnapshot | null; refreshAccessToken?: () => Promise<string | null> }) {
  const api = useMemo(() => new InspectionApi(createMobileHotelOpAiClient({ accessTokenProvider: () => accessToken, refreshAccessToken })), [accessToken, refreshAccessToken]);
  const [items, setItems] = useState<InspectionWorkflow[]>([]); const [selected, setSelected] = useState<InspectionDetail | null>(null); const [answers, setAnswers] = useState<Record<string, boolean>>({}); const [reason, setReason] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const load = async () => { try { setItems(await api.pending()); setMessage(null); } catch (e) { setMessage(e instanceof Error ? e.message : "Unable to load inspections"); } };
  useEffect(() => { void load(); }, [api, currentUser?.hotelId]);
  const open = async (id: string) => { try { const d = await api.detail(id); setSelected(d); setAnswers({}); setReason(""); } catch (e) { setMessage(e instanceof Error ? e.message : "Unable to load inspection"); } };
  const submit = async (result: "PASS" | "REJECT") => { if (!selected || busy) return; const detail = selected; const list: InspectionAnswer[] = (detail.template?.items ?? []).map(i => ({ checklistItemId: i.id, passed: answers[i.id] === true })); if (result === "PASS" && list.some(a => !a.passed)) { setMessage("All checklist items must pass before approval."); return; } if (result === "REJECT" && !reason.trim() && !list.some(a => !a.passed)) { setMessage("Select a failed item or enter a rejection reason."); return; } setBusy(true); try { await api.decide(detail.workflow.id, result, list, reason.trim() || undefined); setSelected(null); await load(); setMessage(result === "PASS" ? "Inspection approved." : "Inspection rejected and returned to the housekeeper."); } catch (e) { setMessage(e instanceof Error ? e.message : "Inspection decision failed"); } finally { setBusy(false); } };
  if (selected) return <ScrollView style={styles.screen}><Text style={styles.title}>Inspection · Room {selected.workflow.roomNumber}</Text><Text style={styles.subtitle}>Assigned housekeeper · {selected.task?.assignment?.displayName ?? "Unassigned"}</Text>{(selected.template?.items ?? []).map(item => <View key={item.id} style={styles.item}><Text style={styles.itemLabel}>{item.label ?? item.code}{item.required || item.mandatory ? " *" : ""}</Text><View style={styles.row}><Pressable style={[styles.choice, answers[item.id] === true && styles.pass]} onPress={() => setAnswers(a => ({ ...a, [item.id]: true }))}><Text>PASS</Text></Pressable><Pressable style={[styles.choice, answers[item.id] === false && styles.fail]} onPress={() => setAnswers(a => ({ ...a, [item.id]: false }))}><Text>FAIL</Text></Pressable></View></View>)}<Text style={styles.subtitle}>Quality score is calculated by the server.</Text><TextInput value={reason} onChangeText={setReason} placeholder="Rejection reason" style={styles.input} multiline/><View style={styles.row}><Pressable disabled={busy} style={styles.button} onPress={() => void submit("PASS")}><Text style={styles.buttonText}>{busy ? "Submitting…" : "Approve"}</Text></Pressable><Pressable disabled={busy} style={[styles.button, styles.reject]} onPress={() => void submit("REJECT")}><Text style={styles.buttonText}>Reject</Text></Pressable></View><Text style={styles.historyTitle}>Inspection history</Text>{selected.history.map(h => <Text key={h.id} style={styles.history}>Attempt {h.attempt}: {h.result} · Quality {h.qualityScore ?? 0}%{h.rejectionReason ? ` · ${h.rejectionReason}` : ""}</Text>)}{message ? <Text style={styles.message}>{message}</Text> : null}</ScrollView>;
  return <ScrollView style={styles.screen}><Text style={styles.title}>Inspections</Text>{message ? <Text style={styles.message}>{message}</Text> : null}{items.length === 0 ? <Text style={styles.subtitle}>No rooms waiting for inspection.</Text> : items.map(item => <Pressable key={item.id} style={styles.card} onPress={() => void open(item.id)}><Text style={styles.room}>Room {item.roomNumber}</Text><Text>Cleaning task · {item.taskId}</Text><Text style={styles.waiting}>Waiting for inspection</Text></Pressable>)}</ScrollView>;
}
const styles = StyleSheet.create({ screen:{ flex:1, padding:spacing.lg, backgroundColor:colors.background }, title:{ fontSize:24, fontWeight:"800", color:colors.text, marginBottom:spacing.sm }, subtitle:{ color:colors.textMuted, marginBottom:spacing.md }, card:{ padding:spacing.md, borderRadius:12, borderWidth:1, borderColor:colors.cardBorder, backgroundColor:colors.surface, marginBottom:spacing.sm }, room:{ fontSize:18, fontWeight:"700", color:colors.text }, waiting:{ color:colors.amber, marginTop:4 }, item:{ paddingVertical:spacing.sm, borderBottomWidth:1, borderBottomColor:colors.cardBorder }, itemLabel:{ color:colors.text, fontWeight:"600" }, row:{ flexDirection:"row", gap:8, marginTop:8 }, choice:{ padding:10, borderWidth:1, borderColor:colors.cardBorder, borderRadius:8 }, pass:{ backgroundColor:colors.green }, fail:{ backgroundColor:colors.red }, input:{ minHeight:60, borderWidth:1, borderColor:colors.cardBorder, borderRadius:8, padding:8, marginVertical:spacing.md }, button:{ padding:12, borderRadius:8, backgroundColor:colors.green }, reject:{ backgroundColor:colors.red }, buttonText:{ color:"white", fontWeight:"700" }, historyTitle:{ marginTop:spacing.lg, fontWeight:"800", color:colors.text }, history:{ marginTop:4, color:colors.textMuted }, message:{ marginVertical:spacing.sm, color:colors.amber } });
