package com.hotelopai.task.application
import com.hotelopai.observability.OperationalObservability
import com.hotelopai.shared.kernel.UuidV7Generator
import com.hotelopai.task.domain.*
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate
import org.springframework.stereotype.Service
import org.springframework.transaction.annotation.Transactional
import java.time.Clock
import java.util.UUID
data class InterruptTaskCommand(val hotelId:UUID,val employeeId:UUID,val employeeDisplayName:String,val activeTaskId:UUID,val interruptingTaskId:UUID,val reason:String,val idempotencyKey:String,val autoStart:Boolean=true)
data class InterruptionResult(val interruptionId:UUID,val pausedTaskId:UUID,val interruptingTaskId:UUID,val status:String)
@Service class SmartInterruptionService(private val jdbc:NamedParameterJdbcTemplate,private val repository:TaskRepository,private val lifecycle:TaskLifecycleService,private val metrics:OperationalObservability,private val clock:Clock=Clock.systemUTC()){
 @Transactional fun interrupt(c:InterruptTaskCommand):InterruptionResult {require(c.reason.isNotBlank()&&c.idempotencyKey.isNotBlank());existing(c.hotelId,c.idempotencyKey)?.let{return it};val active=repository.findByIdAndHotelId(c.activeTaskId,c.hotelId)?:throw TaskNotFoundException(c.activeTaskId);val urgent=repository.findByIdAndHotelId(c.interruptingTaskId,c.hotelId)?:throw TaskNotFoundException(c.interruptingTaskId);require(active.status in setOf(TaskStatus.STARTED,TaskStatus.IN_PROGRESS)){"Previous task is not active"};require(urgent.priority in setOf(TaskPriority.HIGH,TaskPriority.URGENT)){"Interrupting task is not high priority"};require(urgent.status in setOf(TaskStatus.CREATED,TaskStatus.ASSIGNED)){"Interrupting task cannot be activated"};val now=clock.instant();lifecycle.pauseTask(active.id.toString(),c.hotelId,now);if(urgent.status==TaskStatus.CREATED)lifecycle.assignTask(urgent.id.toString(),c.hotelId,AssignTaskCommand(AssignmentCommand(TaskAssigneeType.USER,c.employeeId.toString(),c.employeeDisplayName)),now);if(c.autoStart)lifecycle.startTask(urgent.id.toString(),c.hotelId,now);val id=UuidV7Generator.generate(now);jdbc.update("insert into task_interruption(id,hotel_id,employee_id,paused_task_id,interrupting_task_id,reason,status,idempotency_key,paused_at,created_at) values(:id,:hotel,:employee,:paused,:interrupting,:reason,'ACTIVE',:key,:now,:now)",mapOf("id" to id,"hotel" to c.hotelId,"employee" to c.employeeId,"paused" to active.id,"interrupting" to urgent.id,"reason" to "FLASH_INTERRUPTION:${c.reason}","key" to c.idempotencyKey,"now" to now));metrics.incrementCounter("hotelopai.task.interruption.total","operation" to "interrupt","outcome" to "success");return InterruptionResult(id,active.id,urgent.id,"ACTIVE") }
 @Transactional fun completeAndResume(interruptionId:UUID,hotelId:UUID):InterruptionResult {val row=find(interruptionId,hotelId);if(row.status=="RESUMED"||row.status=="CLOSED")return row;val now=clock.instant();val interrupting=repository.findByIdAndHotelId(row.interruptingTaskId,hotelId)?:throw TaskNotFoundException(row.interruptingTaskId);if(!interrupting.isTerminal())lifecycle.completeTask(interrupting.id.toString(),hotelId,now);val previous=repository.findByIdAndHotelId(row.pausedTaskId,hotelId);val blocked=jdbc.queryForObject("select count(*) from task_interruption other where other.hotel_id=:hotel and other.employee_id=(select employee_id from task_interruption where id=:id) and other.status='ACTIVE' and other.id<>:id",mapOf("hotel" to hotelId,"id" to interruptionId),Long::class.java)?:0;val resumable=previous?.status==TaskStatus.WAITING && row.status=="ACTIVE" && blocked==0L;if(resumable)lifecycle.resumeTask(previous!!.id.toString(),hotelId,now);val status=if(resumable)"RESUMED" else "CLOSED";jdbc.update("update task_interruption set status=:status,resumed_at=:now where id=:id and hotel_id=:hotel",mapOf("status" to status,"now" to now,"id" to interruptionId,"hotel" to hotelId));return row.copy(status=status)}
 private fun find(id:UUID,hotel:UUID)=jdbc.query("select * from task_interruption where id=:id and hotel_id=:hotel",mapOf("id" to id,"hotel" to hotel)){rs,_->InterruptionResult(rs.getObject("id",UUID::class.java),rs.getObject("paused_task_id",UUID::class.java),rs.getObject("interrupting_task_id",UUID::class.java),rs.getString("status"))}.firstOrNull()?:throw NoSuchElementException("Interruption not found")
 private fun existing(hotel:UUID,key:String)=jdbc.query("select * from task_interruption where hotel_id=:hotel and idempotency_key=:key",mapOf("hotel" to hotel,"key" to key)){rs,_->InterruptionResult(rs.getObject("id",UUID::class.java),rs.getObject("paused_task_id",UUID::class.java),rs.getObject("interrupting_task_id",UUID::class.java),rs.getString("status"))}.firstOrNull()
}
