package com.hotelopai.reporting.application
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate
import org.springframework.stereotype.Service
import java.time.Clock
import java.time.Instant
import java.util.UUID
enum class ReportIntent { TASK_VOLUMES, OVERDUE_TASKS, CLEANING_TIME, HOUSEKEEPING_PERFORMANCE, INVENTORY_CONSUMPTION, MINIBAR, DAMAGE, BAD_REVIEW_RISK, WORKLOAD, ASSIGNMENT_PERFORMANCE }
data class ReportFilter(val from:Instant?=null,val to:Instant?=null)
data class ReportTable(val columns:List<String>,val rows:List<List<Any?>>)
data class ManagerReport(val intent:ReportIntent,val summary:String,val kpis:Map<String,Number>,val tables:List<ReportTable>,val explanation:String)
@Service class ManagerReportingService(private val jdbc:NamedParameterJdbcTemplate,private val clock:Clock=Clock.systemUTC()){
 fun interpret(question:String):ReportIntent {val q=question.lowercase();return when{q.contains("overdue")||q.contains("gecik")->ReportIntent.OVERDUE_TASKS;q.contains("clean")||q.contains("housekeep")||q.contains("temiz")->ReportIntent.CLEANING_TIME;q.contains("inventory")||q.contains("stock")||q.contains("stok")->ReportIntent.INVENTORY_CONSUMPTION;q.contains("minibar")->ReportIntent.MINIBAR;q.contains("damage")||q.contains("hasar")->ReportIntent.DAMAGE;q.contains("risk")||q.contains("review")->ReportIntent.BAD_REVIEW_RISK;q.contains("workload")||q.contains("iş yük")->ReportIntent.WORKLOAD;q.contains("assignment")||q.contains("atama")->ReportIntent.ASSIGNMENT_PERFORMANCE;else->ReportIntent.TASK_VOLUMES}}
 fun report(hotelId:UUID,intent:ReportIntent,filter:ReportFilter=ReportFilter()):ManagerReport {val from=filter.from?:clock.instant().minusSeconds(7*86400);val to=filter.to?:clock.instant();require(from<to);val p=mapOf("hotel" to hotelId,"from" to from,"to" to to);return when(intent){
  ReportIntent.TASK_VOLUMES,ReportIntent.OVERDUE_TASKS->{val rows=jdbc.query("select status,count(*) c from task where hotel_id=:hotel and created_at>=:from and created_at<:to group by status order by status",p){rs,_->listOf(rs.getString(1),rs.getLong(2))};val total=rows.sumOf{it[1] as Long};ManagerReport(intent,"$total tasks in the selected period",mapOf("taskCount" to total),listOf(ReportTable(listOf("status","count"),rows)),"Parameterized hotel-scoped task aggregation")}
  ReportIntent.CLEANING_TIME,ReportIntent.HOUSEKEEPING_PERFORMANCE->{val row=jdbc.query("select count(*),coalesce(avg(working_seconds),0),coalesce(avg(paused_seconds),0),count(*) filter(where status in ('COMPLETED','CLOSED')) from housekeeping_workflow where hotel_id=:hotel and created_at>=:from and created_at<:to",p){rs,_->listOf(rs.getLong(1),rs.getDouble(2),rs.getDouble(3),rs.getLong(4))}.first();ManagerReport(intent,"Housekeeping duration uses active segments and excludes pauses",mapOf("workflowCount" to row[0] as Long,"averageWorkingSeconds" to row[1] as Double,"averagePauseSeconds" to row[2] as Double),listOf(ReportTable(listOf("workflows","avgWorkingSeconds","avgPauseSeconds","completed"),listOf(row))),"Predefined housekeeping KPI query")}
  ReportIntent.INVENTORY_CONSUMPTION->{val rows=jdbc.query("select i.name,sum(t.quantity) from inventory_transaction t join inventory_item i on i.id=t.item_id where t.hotel_id=:hotel and t.occurred_at>=:from and t.occurred_at<:to and t.transaction_type in ('CONSUME','MINIBAR_CONSUMPTION','DAMAGE_USAGE') group by i.name order by i.name",p){rs,_->listOf(rs.getString(1),rs.getBigDecimal(2))};ManagerReport(intent,"Inventory consumption by item",mapOf("itemCount" to rows.size),listOf(ReportTable(listOf("item","quantity"),rows)),"Durable inventory ledger aggregation")}
  ReportIntent.MINIBAR->{val count=jdbc.queryForObject("select count(*) from minibar_inspection where hotel_id=:hotel and created_at>=:from and created_at<:to",p,Long::class.java)?:0;ManagerReport(intent,"$count minibar inspections",mapOf("inspectionCount" to count),emptyList(),"Minibar inspection aggregation; revenue is only posted charges")}
  ReportIntent.DAMAGE->{val count=jdbc.queryForObject("select count(*) from damage_report where hotel_id=:hotel and created_at>=:from and created_at<:to",p,Long::class.java)?:0;ManagerReport(intent,"$count damage reports",mapOf("damageCount" to count),emptyList(),"Hotel-scoped damage aggregation")}
  ReportIntent.BAD_REVIEW_RISK->{val rows=jdbc.query("select level,count(*) from guest_risk_assessment where hotel_id=:hotel and assessed_at>=:from and assessed_at<:to group by level",p){rs,_->listOf(rs.getString(1),rs.getLong(2))};ManagerReport(intent,"Rule-based guest risk distribution",mapOf("highRiskCount" to (rows.firstOrNull{it[0]=="HIGH"}?.get(1) as? Long ?:0)),listOf(ReportTable(listOf("level","count"),rows)),"Rule versioned risk assessments")}
  ReportIntent.WORKLOAD,ReportIntent.ASSIGNMENT_PERFORMANCE->{val rows=jdbc.query("select coalesce(assignee_display_name,'Unassigned'),count(*) from task where hotel_id=:hotel and created_at>=:from and created_at<:to group by assignee_display_name order by count(*) desc",p){rs,_->listOf(rs.getString(1),rs.getLong(2))};ManagerReport(intent,"Current task workload distribution",mapOf("assigneeCount" to rows.size),listOf(ReportTable(listOf("assignee","tasks"),rows)),"Task assignment aggregation without sensitive HR data")}
 }}
}
