import assert from "node:assert/strict";
import test from "node:test";
import {availableFloors,canConfirmCsvImport,canOpenAdministration,emptyOnboardingDraft,groupPermissions,parseRoomCsv,selectCsvFile,shouldApplyHotelResponse,validateOnboardingStep} from "./adminLogic.ts";

test("administration visibility is permission based",()=>{assert.equal(canOpenAdministration(["ROOM_VIEW"]),true);assert.equal(canOpenAdministration(["TASK_READ"]),false)});
test("onboarding state validates each step without discarding other steps",()=>{const draft=emptyOnboardingDraft("user-1");assert.match(validateOnboardingStep(0,draft)[0],/Hotel name/);const complete={...draft,name:"Berlin Hotel",code:"BERLIN_1",departments:[{code:"OPS",name:"Operations"}]};assert.deepEqual(validateOnboardingStep(0,complete),[]);assert.equal(complete.departments.length,1)});
test("onboarding catches duplicate and cross-step room references",()=>{const draft={...emptyOnboardingDraft("u"),buildings:[{code:"MAIN",name:"Main",floors:[1]}],rooms:[{buildingCode:"OTHER",floorNumber:1,roomNumber:"101",roomType:"STANDARD"}]};assert.match(validateOnboardingStep(3,draft)[0],/unknown building\/floor/)});
test("permissions are grouped from actual codes and platform scope is distinct",()=>{const groups=groupPermissions([{id:"1",code:"PLATFORM_HOTEL_MANAGE",name:"Platform",assigned:false},{id:"2",code:"ROOM_VIEW",name:"Rooms",assigned:true},{id:"3",code:"TASK_CREATE",name:"Tasks",assigned:false}]);assert.equal(groups[0].name,"Platform");assert.equal(groups.find(g=>g.name==="Hotel Master Data")?.items[0].code,"ROOM_VIEW");assert.equal(groups.find(g=>g.name==="Tasks")?.items.length,1)});
test("CSV selection preview validates header rows and requires explicit caller action",()=>{const preview=parseRoomCsv("building,floor,roomNumber,roomType\nMAIN,1,101,STANDARD\nMAIN,x,,DELUXE");assert.equal(preview.validCount,1);assert.equal(preview.invalidCount,1);assert.match(preview.rows[1].errors.join(" "),/Floor/)});
test("CSV import confirmation is enabled only after a clean preview",()=>{assert.equal(canConfirmCsvImport(parseRoomCsv("building,floor,roomNumber,roomType\nMAIN,1,101,STANDARD")),true);assert.equal(canConfirmCsvImport(parseRoomCsv("building,floor,roomNumber,roomType\nMAIN,x,101,STANDARD")),false)});
test("selecting a CSV file reads and previews without confirming import",()=>{const selected=selectCsvFile("rooms.csv","building,floor,roomNumber,roomType\nMAIN,1,101,STANDARD");assert.equal(selected.fileName,"rooms.csv");assert.equal(selected.preview.validCount,1);assert.equal(selected.confirmed,false)});
test("room floor filters cannot leak floors from another building",()=>{assert.deepEqual(availableFloors([{id:"1",buildingId:"A"},{id:"2",buildingId:"B"}],"B"),[{id:"2",buildingId:"B"}])});
test("late responses from a previously selected hotel are rejected",()=>{assert.equal(shouldApplyHotelResponse(4,5),false);assert.equal(shouldApplyHotelResponse(5,5),true)});
